#!/bin/bash

pName=$1
pVersion=$2

if [[ "$pVersion" != "" ]]
then
    mkdir "$pName@$pVersion" 
    cd ./$pName@$pVersion && mkdir "auxProject" && cd ./auxProject && npm init -f && npm install $pName@$pVersion
else
    mkdir "$pName"
    cd ./$pName && mkdir "auxProject" && cd ./auxProject && npm init -f && npm install $pName
fi
